apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceType: git
  git:
    repo: https://github.com/YOUR_ORG/gke-multicluster-config.git
    branch: main
    dir: clusters/cluster-a
    auth: none
